[project]
name = "satquery-ai"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "accelerate>=1.14.0",
    "bitsandbytes>=0.50.2",
    "einops>=0.8.2",
    "fastapi>=0.141.1",
    "geochat",
    "google-genai>=2.23.0",
    "matplotlib>=3.11.1",
    "peft>=0.20.0",
    "pillow>=12.3.0",
    "python-dotenv>=1.2.0",
    "python-multipart>=0.0.20",
    "scikit-learn>=1.9.0",
    "sentencepiece>=0.2.2",
    "timm>=1.0.29",
    "torch>=2.13.0",
    "transformers>=4.31.0,<5",
    "uvicorn>=0.52.4",
]

[tool.uv.workspace]
members = [
    "geochat",
]

[tool.uv.sources]
geochat = { workspace = true, editable = true }
